name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.6, 3.7, 3.8]
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
    # - name: Set up Python ${{ matrix.python-version }}      
      uses: docker://acidrain/python-poetry:3.6
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with pylint
      run: |
        # stop the build if there are errors
        poetry run pylint -E sal/
    - name: Test with pytest
      run: |
        poetry run python -m pytest sal/tests/